import { useState } from 'react';
import { ArrowRight, LockKeyhole, Scale } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import { api, session } from '../lib/api';
import type { Session } from '../types';

export function Login({ onLogin }: { onLogin: (user: Session) => void }) {
  const [email, setEmail] = useState('admin@deadlineflow.com'); const [password, setPassword] = useState('admin123'); const [error, setError] = useState(''); const [loading, setLoading] = useState(false); const navigate = useNavigate();
  const submit = async (event: React.FormEvent) => { event.preventDefault(); setLoading(true); setError(''); try { const user = await api.login(email, password); session.set(user); onLogin(user); navigate('/dashboard'); } catch (err) { setError(err instanceof Error ? err.message : 'No fue posible iniciar sesión.'); } finally { setLoading(false); } };
  return <main className="grid min-h-screen bg-slate-950 lg:grid-cols-2"><section className="hidden flex-col justify-between bg-gradient-to-br from-cyan-500 via-blue-600 to-indigo-700 p-14 text-white lg:flex"><div className="flex items-center gap-3 text-xl font-bold"><span className="grid size-11 place-items-center rounded-xl bg-white/15"><Scale /></span>Deadlineflow</div><div><p className="max-w-lg text-5xl font-bold leading-tight">El control de cada plazo, sin perder el ritmo.</p><p className="mt-6 max-w-md text-lg text-cyan-50">Una vista clara para que tu equipo legal pueda priorizar, actuar y avanzar.</p></div><p className="text-sm text-cyan-100">Gestión legal inteligente</p></section><section className="flex items-center justify-center bg-slate-50 p-6"><form onSubmit={submit} className="w-full max-w-md rounded-3xl bg-white p-8 shadow-xl shadow-slate-900/5 sm:p-10"><div className="mb-9"><div className="mb-6 flex items-center gap-3 lg:hidden"><span className="grid size-10 place-items-center rounded-xl bg-cyan-500 text-white"><Scale /></span><b>Deadlineflow</b></div><p className="text-sm font-semibold text-cyan-600">BIENVENIDO</p><h1 className="mt-2 text-3xl font-bold tracking-tight">Ingresa a tu espacio</h1><p className="mt-2 text-slate-500">Gestiona lo importante con confianza.</p></div><label className="field-label">Correo electrónico<input className="field" type="email" value={email} onChange={e => setEmail(e.target.value)} required /></label><label className="field-label mt-5">Contraseña<input className="field" type="password" value={password} onChange={e => setPassword(e.target.value)} minLength={6} required /></label>{error && <p className="mt-4 rounded-lg bg-rose-50 p-3 text-sm text-rose-700">{error}</p>}<button disabled={loading} className="btn-primary mt-7 w-full">{loading ? 'Ingresando…' : <>Ingresar <ArrowRight size={18} /></>}</button><p className="mt-6 flex items-center gap-2 text-xs text-slate-400"><LockKeyhole size={14} />Acceso seguro para el equipo autorizado</p></form></section></main>;
}
