package com.utp.deadlineflow.entity;

public enum TipoEvento {
    CREACION_EXPEDIENTE, CREACION_TAREA, CAMBIO_ESTADO_TAREA,
    CREACION_PLAZO, ANULACION_PLAZO, REASIGNACION_TAREA, CARGA_DOCUMENTO
}
